In [1]:
import numpy as np 
import pandas as pd
%load_ext autoreload
%autoreload 2
from impute_helpers import impute_with_closest_price, impute_neighbor_with_closest_price, impute_with_closest_year, impute_with_mode, impute_subset_neighbor_with_closest_price

In [35]:
housingData = pd.read_csv('../../data/Ames_Housing_Price_Data.csv',index_col = 0)
housingData=housingData.reset_index(drop=True)

In [36]:
def check_empty_vals():
    cols=housingData.columns
    for col in cols:
        null_count=pd.isnull(housingData[col]).sum()
        if null_count>0:
            print(col,null_count)
        
        
check_empty_vals()

LotFrontage 462
Alley 2412
MasVnrType 14
MasVnrArea 14
BsmtQual 69
BsmtCond 69
BsmtExposure 71
BsmtFinType1 69
BsmtFinSF1 1
BsmtFinType2 70
BsmtFinSF2 1
BsmtUnfSF 1
TotalBsmtSF 1
Electrical 1
BsmtFullBath 2
BsmtHalfBath 2
FireplaceQu 1241
GarageType 127
GarageYrBlt 129
GarageFinish 129
GarageCars 1
GarageArea 1
GarageQual 129
GarageCond 129
PoolQC 2571
Fence 2055
MiscFeature 2483

<h1>Remove non residential homes</h1>

In [37]:
housingData['MSZoning'].unique()
housingData=housingData[housingData['MSZoning'].isin(["RH","RM","RL"])]

<h1>Impute LotFrontage</h1>

In [38]:
housingData['LotFrontage'] = housingData['LotFrontage'].fillna(housingData.groupby('Neighborhood')['LotFrontage'].transform('mean').round(2))

In [6]:
housingData.loc[(housingData['Neighborhood']=="GrnHill") & (pd.isnull(housingData['LotFrontage'])), 'LotFrontage'] = housingData[housingData['Neighborhood']=="NoRidge"]['LotFrontage'].mean()
housingData.loc[(housingData['Neighborhood']=="Landmrk") & (pd.isnull(housingData['LotFrontage'])), 'LotFrontage'] = housingData[housingData['Neighborhood']=="Greens"]['LotFrontage'].mean()

<h1>Impute MasVnrArea and MasVnrType with value from property with closest prices</h1>

In [39]:
impute_neighbor_with_closest_price(housingData,'MasVnrType')
impute_neighbor_with_closest_price(housingData,'MasVnrArea')

,PID,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,909176150,856,126000,30,RL,58.77,7890,Pave,NaN,Reg,...,166,0,NaN,NaN,NaN,0,3,2010,WD,Normal
1,905476230,1049,139500,120,RL,42.00,4235,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,2,2009,WD,Normal
3,535377150,1039,114000,70,RL,80.00,8146,Pave,NaN,Reg,...,111,0,NaN,NaN,NaN,0,5,2009,WD,Normal
4,534177230,1665,227000,60,RL,70.00,8400,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,11,2009,WD,Normal
5,908128060,1922,198500,85,RL,64.00,7301,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,7,2009,ConLD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,903205040,952,121000,30,RL,55.95,8854,Pave,NaN,Reg,...,40,0,NaN,NaN,NaN,0,5,2009,WD,Normal
2576,905402060,1733,139600,20,RL,65.49,13680,Pave,NaN,IR1,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
2577,909275030,2002,145000,90,RH,82.00,6270,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
2578,907192040,1842,217500,60,RL,69.98,8826,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,7,2007,WD,Normal
2579,906223180,1911,215000,60,RL,80.00,9554,Pave,NaN,IR1,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal

<h1>Impute Electrical with value from closest year build</h1>

In [40]:
impute_with_closest_year(housingData,'Electrical')

,PID,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,909176150,856,126000,30,RL,58.77,7890,Pave,NaN,Reg,...,166,0,NaN,NaN,NaN,0,3,2010,WD,Normal
1,905476230,1049,139500,120,RL,42.00,4235,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,2,2009,WD,Normal
3,535377150,1039,114000,70,RL,80.00,8146,Pave,NaN,Reg,...,111,0,NaN,NaN,NaN,0,5,2009,WD,Normal
4,534177230,1665,227000,60,RL,70.00,8400,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,11,2009,WD,Normal
5,908128060,1922,198500,85,RL,64.00,7301,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,7,2009,ConLD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,903205040,952,121000,30,RL,55.95,8854,Pave,NaN,Reg,...,40,0,NaN,NaN,NaN,0,5,2009,WD,Normal
2576,905402060,1733,139600,20,RL,65.49,13680,Pave,NaN,IR1,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
2577,909275030,2002,145000,90,RH,82.00,6270,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
2578,907192040,1842,217500,60,RL,69.98,8826,Pave,NaN,Reg,...,0,0,NaN,NaN,NaN,0,7,2007,WD,Normal
2579,906223180,1911,215000,60,RL,80.00,9554,Pave,NaN,IR1,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal

<h1>Remove Alley</h1>

In [41]:
housingData.drop('Alley',axis=1, inplace=True)

<h1>Impute Basement square footage with price and neighbor</h1>

In [42]:
impute_neighbor_with_closest_price(housingData,'TotalBsmtSF')

,PID,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,909176150,856,126000,30,RL,58.77,7890,Pave,Reg,Lvl,...,166,0,NaN,NaN,NaN,0,3,2010,WD,Normal
1,905476230,1049,139500,120,RL,42.00,4235,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,2,2009,WD,Normal
3,535377150,1039,114000,70,RL,80.00,8146,Pave,Reg,Lvl,...,111,0,NaN,NaN,NaN,0,5,2009,WD,Normal
4,534177230,1665,227000,60,RL,70.00,8400,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2009,WD,Normal
5,908128060,1922,198500,85,RL,64.00,7301,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2009,ConLD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,903205040,952,121000,30,RL,55.95,8854,Pave,Reg,Lvl,...,40,0,NaN,NaN,NaN,0,5,2009,WD,Normal
2576,905402060,1733,139600,20,RL,65.49,13680,Pave,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
2577,909275030,2002,145000,90,RH,82.00,6270,Pave,Reg,HLS,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
2578,907192040,1842,217500,60,RL,69.98,8826,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2007,WD,Normal
2579,906223180,1911,215000,60,RL,80.00,9554,Pave,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal

<h1>Impute BsmtExposure</h1> <p>Impute with mode of neighbor if basement square footage more than 0 --otherwise impute NA</p>

In [43]:
bsmtexp=housingData[pd.isnull(housingData['BsmtExposure']) & (housingData['TotalBsmtSF']>0)].index
groupingcol="Neighborhood"
missingcol="BsmtExposure"
for idx in bsmtexp:
    modevalue=housingData.groupby(groupingcol)[missingcol].agg(pd.Series.mode)
    housingData.loc[idx,missingcol]=modevalue[housingData.loc[idx,groupingcol]]
housingData.loc[(pd.isnull(housingData['BsmtExposure'])), 'BsmtExposure']="NA"

<h1>Impute GarageCars and GarageArea</h1>

In [44]:
impute_neighbor_with_closest_price(housingData,'GarageCars')
impute_neighbor_with_closest_price(housingData,'GarageArea')

,PID,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,909176150,856,126000,30,RL,58.77,7890,Pave,Reg,Lvl,...,166,0,NaN,NaN,NaN,0,3,2010,WD,Normal
1,905476230,1049,139500,120,RL,42.00,4235,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,2,2009,WD,Normal
3,535377150,1039,114000,70,RL,80.00,8146,Pave,Reg,Lvl,...,111,0,NaN,NaN,NaN,0,5,2009,WD,Normal
4,534177230,1665,227000,60,RL,70.00,8400,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2009,WD,Normal
5,908128060,1922,198500,85,RL,64.00,7301,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2009,ConLD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,903205040,952,121000,30,RL,55.95,8854,Pave,Reg,Lvl,...,40,0,NaN,NaN,NaN,0,5,2009,WD,Normal
2576,905402060,1733,139600,20,RL,65.49,13680,Pave,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
2577,909275030,2002,145000,90,RH,82.00,6270,Pave,Reg,HLS,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
2578,907192040,1842,217500,60,RL,69.98,8826,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2007,WD,Normal
2579,906223180,1911,215000,60,RL,80.00,9554,Pave,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal

<h1>Impute basement values for index 912</h1>

In [45]:
impute_neighbor_with_closest_price(housingData,'BsmtFinSF1')
impute_neighbor_with_closest_price(housingData,'BsmtFinSF2')
impute_neighbor_with_closest_price(housingData,'BsmtUnfSF')

,PID,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,909176150,856,126000,30,RL,58.77,7890,Pave,Reg,Lvl,...,166,0,NaN,NaN,NaN,0,3,2010,WD,Normal
1,905476230,1049,139500,120,RL,42.00,4235,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,2,2009,WD,Normal
3,535377150,1039,114000,70,RL,80.00,8146,Pave,Reg,Lvl,...,111,0,NaN,NaN,NaN,0,5,2009,WD,Normal
4,534177230,1665,227000,60,RL,70.00,8400,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2009,WD,Normal
5,908128060,1922,198500,85,RL,64.00,7301,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2009,ConLD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,903205040,952,121000,30,RL,55.95,8854,Pave,Reg,Lvl,...,40,0,NaN,NaN,NaN,0,5,2009,WD,Normal
2576,905402060,1733,139600,20,RL,65.49,13680,Pave,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
2577,909275030,2002,145000,90,RH,82.00,6270,Pave,Reg,HLS,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
2578,907192040,1842,217500,60,RL,69.98,8826,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2007,WD,Normal
2579,906223180,1911,215000,60,RL,80.00,9554,Pave,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal

<h1>Impute BsmtFullBath and BsmtHalfBath to 0</h1><p>Index 912 has unfinished basement, Index 2308 has no basement</p>

In [15]:
housingData.loc[(pd.isnull(housingData['BsmtHalfBath'])), 'BsmtHalfBath']=0
housingData.loc[(pd.isnull(housingData['BsmtFullBath'])), 'BsmtFullBath']=0

<h1>Impute BsmtQual, BsmtCond, BsmtFinType1, BsmtFinType2</h1><p>Impute neighborhood value for those with Basement square footage otherwise impute NA</p>

In [18]:
bsmtqual=housingData[pd.isnull(housingData['BsmtQual']) & (housingData['TotalBsmtSF']>0)]
impute_subset_neighbor_with_closest_price(housingData,bsmtqual,'BsmtQual')
housingData.loc[(pd.isnull(housingData['BsmtQual'])), 'BsmtQual']="NA"
bsmtcond=housingData[pd.isnull(housingData['BsmtCond']) & (housingData['TotalBsmtSF']>0)]
impute_subset_neighbor_with_closest_price(housingData,bsmtcond,'BsmtCond')
housingData.loc[(pd.isnull(housingData['BsmtCond'])), 'BsmtCond']="NA"
bsmtfintype1_total=housingData[pd.isnull(housingData['BsmtFinType1']) & (housingData['TotalBsmtSF']>0)]
impute_subset_neighbor_with_closest_price(housingData,bsmtfintype1_total,'BsmtFinType1')
housingData.loc[(pd.isnull(housingData['BsmtFinType1'])), 'BsmtFinType1']="NA"
bsmtfintype2_total=housingData[pd.isnull(housingData['BsmtFinType2']) & (housingData['TotalBsmtSF']>0)]
impute_subset_neighbor_with_closest_price(housingData,bsmtfintype2_total,'BsmtFinType1')
housingData.loc[pd.isnull(housingData['BsmtFinType2']) & (housingData['BsmtFinSF2']>0),'BsmtFinType2']="Rec"
housingData.loc[(pd.isnull(housingData['BsmtFinType2'])), 'BsmtFinType2']="NA"

<h1>Impute Garage values</h1>

In [19]:
garagetype=housingData[pd.isnull(housingData['GarageType']) & (housingData['GarageArea']>0)]
housingData.loc[(pd.isnull(housingData['GarageType'])), 'GarageType']="NA"
garageyear=housingData[pd.isnull(housingData['GarageYrBlt']) & (housingData['GarageArea']>0)]
for idx in garageyear.index:
    housingData.loc[idx,'GarageYrBlt']=housingData.loc[idx,'YearBuilt']
housingData.loc[(pd.isnull(housingData['GarageYrBlt'])), 'GarageYrBlt']=0
garagequal=housingData[pd.isnull(housingData['GarageQual']) & (housingData['GarageArea']>0)]
housingData.loc[pd.isnull(housingData['GarageQual']) & (housingData['GarageArea']>0),'GarageQual']="TA"
garagecond=housingData[pd.isnull(housingData['GarageCond']) & (housingData['GarageArea']>0)]
housingData.loc[pd.isnull(housingData['GarageCond']) & (housingData['GarageArea']>0),'GarageCond']="TA"
garagefinish=housingData[pd.isnull(housingData['GarageFinish']) & (housingData['GarageArea']>0)]
impute_subset_neighbor_with_closest_price(housingData,garagefinish,'GarageFinish')
housingData.loc[pd.isnull(housingData['GarageFinish']) & (housingData['GarageArea']>0),'GarageFinish']="Unf"
housingData.loc[(pd.isnull(housingData['GarageQual'])), 'GarageQual']="NA"
housingData.loc[(pd.isnull(housingData['GarageCond'])), 'GarageCond']="NA"
housingData.loc[(pd.isnull(housingData['GarageFinish'])), 'GarageFinish']="NA"

<h1>Impute FireplaceQu poolQC Fence MiscFeature</h1>

In [21]:
fireplaceQU=housingData[pd.isnull(housingData['FireplaceQu']) & (housingData['Fireplaces']>0)]
housingData.loc[pd.isnull(housingData['FireplaceQu']) & (housingData['Fireplaces']==0),'FireplaceQu']="NA"
poolQC=housingData[pd.isnull(housingData['PoolQC']) & (housingData['PoolArea']>0)]
housingData.loc[pd.isnull(housingData['PoolQC']) & (housingData['PoolArea']==0),'PoolQC']="NA"
housingData.loc[pd.isnull(housingData['Fence']),"Fence"]="NA"
housingData['MiscFeature'] = housingData.MiscFeature.map(lambda t:0 if pd.isnull(t) else 1)

In [30]:
def check_empty_vals():
    cols=housingData.columns
    empty_numeric_cols=[]
    empty_categorical_cols=[]
    for col in cols:
        null_count=pd.isnull(housingData[col]).sum()
        if null_count > 0:
            print(col,null_count)

check_empty_vals()
housingData.columns

Index(['PID', 'GrLivArea', 'SalePrice', 'MSSubClass', 'MSZoning',
       'LotFrontage', 'LotArea', 'Street', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF',
       '2ndFlrSF', 'LowQualFinSF', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [27]:
housingData.to_csv("./imputeImpl_housingData.csv")